### ISSUE TITLE
command not found : complete when using bash completion

### ISSUE THREAD

**Issue by osaris** [eddiezane/lunchy#57]
Hello,

I have added the code for completion in my .bash_profile file and when I source it, I have the following error :

```rvm/gems/ruby-2.0.0-p598/gems/lunchy-0.10.1/lib/../extras/lunchy-completion.bash:18: command not found: complete```

Looks like the command used there https://github.com/eddiezane/lunchy/blob/5640b8a47720adeb085924994aaabe07c80ee212/extras/lunchy-completion.bash#L18 isn't available on my system (OSX 10.10.4).

Thanks for your help.

**Comment by bunnymatic** [comment]
Are you using `bash` as your shell?  If not, this completion script won't help and you should probably leave it out of your profile/bashrc.

If you are using `bash`, do you have `bash_completion` installed?
If not, or you can try installing it via [homebrew](http://brew.sh).

You can check to see if `bash_completion` is available (assuming you have homebrew).

`brew list`

you should see `bash_completion` in the list.  If not then install it

`brew install bash_completion`

Then restart your terminal and see if that works.

If you get this far and things are still not working, let us know and we'll try to get it figured out.  Please include the version of bash, the list of brew packages.

**Comment by osaris** [comment]
My bad, I'm using zsh :-( Thanks for your quick answer.

**Comment by bunnymatic** [comment]
i don't know how zsh completion works, but it seems like there must be a mechanism.  If you'd like to write a completion script, we'd be happy to roll it in.

**Comment by osaris** [comment]
zsh have a bash completion script compatibility mode, you need to run :
```
autoload bashcompinit
bashcompinit
```
before sourcing the bash completion file. I have tested it and it works partially (listing the lunchy command is ok but not listing of the plist files).

I'll investigate and try to find  a solution to have a working completion for ZSH.

**Comment by osaris** [comment]
Proposal in #59

**Comment by eddiezane** [comment]
Closed via #59

**Comment by ivanyang1984** [comment]
that is cool!

**Comment by secbitchris** [comment]
Is there a workaround for ZSH yet?

**Comment by bunnymatic** [comment]
Have you tried the latest?  It looks like that has been solved by #3236 (referenced above).  Try installing the latest version, follow the zsh completion instructions and see if that works.

**Comment by fujian26** [comment]
autoload bashcompinit
bashcompinit
I tried this, but it didn't work for me.

**Comment by phaberest** [comment]
For those who were not able to make it work, just paste those two lines in your `~/.zshrc` file right before the `source filethathascompletion.bash` line

**Comment by Tcharl** [comment]
At the end of the zshrc ^^. Putting it on the beginning does not fix the issue

**Comment by Marthyn** [comment]
```
autoload bashcompinit
bashcompinit
```
On top of `.zshrc` works! 👍

**Comment by chrispruitt** [comment]
this is the only thing that worked for me.
got it from here https://github.com/creationix/nvm/pull/1780/files

added this to the top of my .zshrc
```
autoload -U +X bashcompinit && bashcompinit
autoload -U +X compinit && compinit
```

**Comment by Sn0wl3r0ker** [comment]
> this is the only thing that worked for me.
> got it from here https://github.com/creationix/nvm/pull/1780/files
> 
> added this to the top of my `.zshrc`
> 
> ```
> autoload -U +X bashcompinit && bashcompinit
> autoload -U +X compinit && compinit
> ```

thx bro! finally works~

**Comment by kayengar** [comment]
> this is the only thing that worked for me.
> got it from here https://github.com/creationix/nvm/pull/1780/files
> 
> added this to the top of my `.zshrc`
> 
> ```
> autoload -U +X bashcompinit && bashcompinit
> autoload -U +X compinit && compinit
> ```

This for sure worked!

**Comment by 178me** [comment]
autoload bashcompinit && bashcompinit
The same principle, this method will be more concise

**Comment by martinsotirov** [comment]
> > this is the only thing that worked for me.
> > got it from here https://github.com/creationix/nvm/pull/1780/files
> > added this to the top of my `.zshrc`
> > ```
> > autoload -U +X bashcompinit && bashcompinit
> > autoload -U +X compinit && compinit
> > ```
> 
> This for sure worked!

This doesn't work for me on macOS 14.2. Neither at the top, nor at the bottom of `.zshrc`.

**Comment by martinsotirov** [comment]
I'm on macOS 14.6.1 now, still doesn't work.
